services:
  - type: web
    name: docutalk
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run app.py --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
